//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.def;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}SEC_LEG"/>
 *         &lt;element ref="{}REISSUE_INFO"/>
 *         &lt;element ref="{}TXS_CSH_INFO"/>
 *         &lt;element ref="{}RECEIVER_BANK"/>
 *         &lt;element ref="{}STLM_PRTY"/>
 *         &lt;element ref="{}BILL_FEES"/>
 *       &lt;/choice>
 *       &lt;attribute name="PRTY_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STLM_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CB_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seclegOrREISSUEINFOOrTXSCSHINFO"
})
@XmlRootElement(name = "CONS_REI_INST")
public class CONSREIINST {

    @XmlElements({
        @XmlElement(name = "SEC_LEG", type = SECLEG.class),
        @XmlElement(name = "REISSUE_INFO", type = REISSUEINFO.class),
        @XmlElement(name = "TXS_CSH_INFO", type = TXSCSHINFO.class),
        @XmlElement(name = "RECEIVER_BANK", type = RECEIVERBANK.class),
        @XmlElement(name = "STLM_PRTY", type = STLMPRTY.class),
        @XmlElement(name = "BILL_FEES", type = BILLFEES.class)
    })
    protected List<Object> seclegOrREISSUEINFOOrTXSCSHINFO;
    @XmlAttribute(name = "PRTY_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String prtyid;
    @XmlAttribute(name = "STLM_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String stlmdt;
    @XmlAttribute(name = "CB_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String cbid;

    /**
     * Gets the value of the seclegOrREISSUEINFOOrTXSCSHINFO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the seclegOrREISSUEINFOOrTXSCSHINFO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSECLEGOrREISSUEINFOOrTXSCSHINFO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SECLEG }
     * {@link REISSUEINFO }
     * {@link TXSCSHINFO }
     * {@link RECEIVERBANK }
     * {@link STLMPRTY }
     * {@link BILLFEES }
     * 
     * 
     */
    public List<Object> getSECLEGOrREISSUEINFOOrTXSCSHINFO() {
        if (seclegOrREISSUEINFOOrTXSCSHINFO == null) {
            seclegOrREISSUEINFOOrTXSCSHINFO = new ArrayList<Object>();
        }
        return this.seclegOrREISSUEINFOOrTXSCSHINFO;
    }

    /**
     * Gets the value of the prtyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRTYID() {
        return prtyid;
    }

    /**
     * Sets the value of the prtyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRTYID(String value) {
        this.prtyid = value;
    }

    /**
     * Gets the value of the stlmdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTLMDT() {
        return stlmdt;
    }

    /**
     * Sets the value of the stlmdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTLMDT(String value) {
        this.stlmdt = value;
    }

    /**
     * Gets the value of the cbid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBID() {
        return cbid;
    }

    /**
     * Sets the value of the cbid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBID(String value) {
        this.cbid = value;
    }

}
