//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ISIN" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDM_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NUM_SERIAL" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BOOK_NUM" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RCR_BK_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RCR_ACCT_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RCR_ACCT_NM" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HEAL_INSU_FEE" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CSH_SYS">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="TWD"/>
 *             &lt;enumeration value="USD"/>
 *             &lt;enumeration value="AUD"/>
 *             &lt;enumeration value="EUR"/>
 *             &lt;enumeration value="JPY"/>
 *             &lt;enumeration value="CNY"/>
 *             &lt;enumeration value="ZAR"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SWIFT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RCR_EN_ACTNM" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="INVS_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ADD_NARR" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "HLI")
public class HLI {

    @XmlAttribute(name = "ISIN", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String isin;
    @XmlAttribute(name = "RDM_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmdt;
    @XmlAttribute(name = "NUM_SERIAL", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String numserial;
    @XmlAttribute(name = "BOOK_NUM", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String booknum;
    @XmlAttribute(name = "RCR_BK_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rcrbkid;
    @XmlAttribute(name = "RCR_ACCT_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rcracctid;
    @XmlAttribute(name = "RCR_ACCT_NM")
    @XmlSchemaType(name = "anySimpleType")
    protected String rcracctnm;
    @XmlAttribute(name = "HEAL_INSU_FEE")
    @XmlSchemaType(name = "anySimpleType")
    protected String healinsufee;
    @XmlAttribute(name = "CSH_SYS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cshsys;
    @XmlAttribute(name = "SWIFT")
    @XmlSchemaType(name = "anySimpleType")
    protected String swift;
    @XmlAttribute(name = "RCR_EN_ACTNM")
    @XmlSchemaType(name = "anySimpleType")
    protected String rcrenactnm;
    @XmlAttribute(name = "INVS_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String invsid;
    @XmlAttribute(name = "ADD_NARR")
    @XmlSchemaType(name = "anySimpleType")
    protected String addnarr;

    /**
     * Gets the value of the isin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISIN() {
        return isin;
    }

    /**
     * Sets the value of the isin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISIN(String value) {
        this.isin = value;
    }

    /**
     * Gets the value of the rdmdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMDT() {
        return rdmdt;
    }

    /**
     * Sets the value of the rdmdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMDT(String value) {
        this.rdmdt = value;
    }

    /**
     * Gets the value of the numserial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMSERIAL() {
        return numserial;
    }

    /**
     * Sets the value of the numserial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMSERIAL(String value) {
        this.numserial = value;
    }

    /**
     * Gets the value of the booknum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBOOKNUM() {
        return booknum;
    }

    /**
     * Sets the value of the booknum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBOOKNUM(String value) {
        this.booknum = value;
    }

    /**
     * Gets the value of the rcrbkid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRCRBKID() {
        return rcrbkid;
    }

    /**
     * Sets the value of the rcrbkid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRCRBKID(String value) {
        this.rcrbkid = value;
    }

    /**
     * Gets the value of the rcracctid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRCRACCTID() {
        return rcracctid;
    }

    /**
     * Sets the value of the rcracctid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRCRACCTID(String value) {
        this.rcracctid = value;
    }

    /**
     * Gets the value of the rcracctnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRCRACCTNM() {
        return rcracctnm;
    }

    /**
     * Sets the value of the rcracctnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRCRACCTNM(String value) {
        this.rcracctnm = value;
    }

    /**
     * Gets the value of the healinsufee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHEALINSUFEE() {
        return healinsufee;
    }

    /**
     * Sets the value of the healinsufee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHEALINSUFEE(String value) {
        this.healinsufee = value;
    }

    /**
     * Gets the value of the cshsys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSHSYS() {
        return cshsys;
    }

    /**
     * Sets the value of the cshsys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSHSYS(String value) {
        this.cshsys = value;
    }

    /**
     * Gets the value of the swift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWIFT() {
        return swift;
    }

    /**
     * Sets the value of the swift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWIFT(String value) {
        this.swift = value;
    }

    /**
     * Gets the value of the rcrenactnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRCRENACTNM() {
        return rcrenactnm;
    }

    /**
     * Sets the value of the rcrenactnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRCRENACTNM(String value) {
        this.rcrenactnm = value;
    }

    /**
     * Gets the value of the invsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVSID() {
        return invsid;
    }

    /**
     * Sets the value of the invsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVSID(String value) {
        this.invsid = value;
    }

    /**
     * Gets the value of the addnarr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDNARR() {
        return addnarr;
    }

    /**
     * Sets the value of the addnarr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDNARR(String value) {
        this.addnarr = value;
    }

}
