//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="REF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PRTY_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ACCT_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CPRTY_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CACCT_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ISIN" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SEC_AMT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ORG_SEC_AMT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="INH_TYPE" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="5"/>
 *             &lt;enumeration value="6"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ISS_MARK">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Y"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="OCC_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="APP_DT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RST">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "INHT")
public class INHT {

    @XmlAttribute(name = "REF")
    @XmlSchemaType(name = "anySimpleType")
    protected String ref;
    @XmlAttribute(name = "PRTY_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String prtyid;
    @XmlAttribute(name = "ACCT_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String acctid;
    @XmlAttribute(name = "CPRTY_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String cprtyid;
    @XmlAttribute(name = "CACCT_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String cacctid;
    @XmlAttribute(name = "ISIN", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String isin;
    @XmlAttribute(name = "SEC_AMT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String secamt;
    @XmlAttribute(name = "ORG_SEC_AMT")
    @XmlSchemaType(name = "anySimpleType")
    protected String orgsecamt;
    @XmlAttribute(name = "INH_TYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inhtype;
    @XmlAttribute(name = "ISS_MARK")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String issmark;
    @XmlAttribute(name = "OCC_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String occdt;
    @XmlAttribute(name = "APP_DT")
    @XmlSchemaType(name = "anySimpleType")
    protected String appdt;
    @XmlAttribute(name = "RST")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rst;

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREF() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREF(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the prtyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRTYID() {
        return prtyid;
    }

    /**
     * Sets the value of the prtyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRTYID(String value) {
        this.prtyid = value;
    }

    /**
     * Gets the value of the acctid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCTID() {
        return acctid;
    }

    /**
     * Sets the value of the acctid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCTID(String value) {
        this.acctid = value;
    }

    /**
     * Gets the value of the cprtyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPRTYID() {
        return cprtyid;
    }

    /**
     * Sets the value of the cprtyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPRTYID(String value) {
        this.cprtyid = value;
    }

    /**
     * Gets the value of the cacctid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCACCTID() {
        return cacctid;
    }

    /**
     * Sets the value of the cacctid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCACCTID(String value) {
        this.cacctid = value;
    }

    /**
     * Gets the value of the isin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISIN() {
        return isin;
    }

    /**
     * Sets the value of the isin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISIN(String value) {
        this.isin = value;
    }

    /**
     * Gets the value of the secamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECAMT() {
        return secamt;
    }

    /**
     * Sets the value of the secamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECAMT(String value) {
        this.secamt = value;
    }

    /**
     * Gets the value of the orgsecamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGSECAMT() {
        return orgsecamt;
    }

    /**
     * Sets the value of the orgsecamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGSECAMT(String value) {
        this.orgsecamt = value;
    }

    /**
     * Gets the value of the inhtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINHTYPE() {
        return inhtype;
    }

    /**
     * Sets the value of the inhtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINHTYPE(String value) {
        this.inhtype = value;
    }

    /**
     * Gets the value of the issmark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSMARK() {
        return issmark;
    }

    /**
     * Sets the value of the issmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSMARK(String value) {
        this.issmark = value;
    }

    /**
     * Gets the value of the occdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOCCDT() {
        return occdt;
    }

    /**
     * Sets the value of the occdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOCCDT(String value) {
        this.occdt = value;
    }

    /**
     * Gets the value of the appdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPDT() {
        return appdt;
    }

    /**
     * Sets the value of the appdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPDT(String value) {
        this.appdt = value;
    }

    /**
     * Gets the value of the rst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRST() {
        return rst;
    }

    /**
     * Sets the value of the rst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRST(String value) {
        this.rst = value;
    }

}
