//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.def;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.metrics.xml.def package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _STLMDT_QNAME = new QName("", "STLM_DT");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.metrics.xml.def
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MODREPO }
     * 
     */
    public MODREPO createMODREPO() {
        return new MODREPO();
    }

    /**
     * Create an instance of {@link CSHLEG }
     * 
     */
    public CSHLEG createCSHLEG() {
        return new CSHLEG();
    }

    /**
     * Create an instance of {@link SECLEG }
     * 
     */
    public SECLEG createSECLEG() {
        return new SECLEG();
    }

    /**
     * Create an instance of {@link SECGENLEG }
     * 
     */
    public SECGENLEG createSECGENLEG() {
        return new SECGENLEG();
    }

    /**
     * Create an instance of {@link SECUNITSLEG }
     * 
     */
    public SECUNITSLEG createSECUNITSLEG() {
        return new SECUNITSLEG();
    }

    /**
     * Create an instance of {@link FRSTLEG }
     * 
     */
    public FRSTLEG createFRSTLEG() {
        return new FRSTLEG();
    }

    /**
     * Create an instance of {@link TAXIMP }
     * 
     */
    public TAXIMP createTAXIMP() {
        return new TAXIMP();
    }

    /**
     * Create an instance of {@link SCNDLEG }
     * 
     */
    public SCNDLEG createSCNDLEG() {
        return new SCNDLEG();
    }

    /**
     * Create an instance of {@link BDLEG }
     * 
     */
    public BDLEG createBDLEG() {
        return new BDLEG();
    }

    /**
     * Create an instance of {@link REINOTE }
     * 
     */
    public REINOTE createREINOTE() {
        return new REINOTE();
    }

    /**
     * Create an instance of {@link CSHNOTICE }
     * 
     */
    public CSHNOTICE createCSHNOTICE() {
        return new CSHNOTICE();
    }

    /**
     * Create an instance of {@link PRTY }
     * 
     */
    public PRTY createPRTY() {
        return new PRTY();
    }

    /**
     * Create an instance of {@link STLMPRTY }
     * 
     */
    public STLMPRTY createSTLMPRTY() {
        return new STLMPRTY();
    }

    /**
     * Create an instance of {@link CPRTY }
     * 
     */
    public CPRTY createCPRTY() {
        return new CPRTY();
    }

    /**
     * Create an instance of {@link BCSSUSER }
     * 
     */
    public BCSSUSER createBCSSUSER() {
        return new BCSSUSER();
    }

    /**
     * Create an instance of {@link MORTGAGEBUYSEL }
     * 
     */
    public MORTGAGEBUYSEL createMORTGAGEBUYSEL() {
        return new MORTGAGEBUYSEL();
    }

    /**
     * Create an instance of {@link BUY }
     * 
     */
    public BUY createBUY() {
        return new BUY();
    }

    /**
     * Create an instance of {@link SELL }
     * 
     */
    public SELL createSELL() {
        return new SELL();
    }

    /**
     * Create an instance of {@link ERINST }
     * 
     */
    public ERINST createERINST() {
        return new ERINST();
    }

    /**
     * Create an instance of {@link UNDW }
     * 
     */
    public UNDW createUNDW() {
        return new UNDW();
    }

    /**
     * Create an instance of {@link RECEIVERBANK }
     * 
     */
    public RECEIVERBANK createRECEIVERBANK() {
        return new RECEIVERBANK();
    }

    /**
     * Create an instance of {@link UNDERWRITINGPART }
     * 
     */
    public UNDERWRITINGPART createUNDERWRITINGPART() {
        return new UNDERWRITINGPART();
    }

    /**
     * Create an instance of {@link RPCH }
     * 
     */
    public RPCH createRPCH() {
        return new RPCH();
    }

    /**
     * Create an instance of {@link MORTGAGEREGEX }
     * 
     */
    public MORTGAGEREGEX createMORTGAGEREGEX() {
        return new MORTGAGEREGEX();
    }

    /**
     * Create an instance of {@link DENOMINATION }
     * 
     */
    public DENOMINATION createDENOMINATION() {
        return new DENOMINATION();
    }

    /**
     * Create an instance of {@link CSHADVICE }
     * 
     */
    public CSHADVICE createCSHADVICE() {
        return new CSHADVICE();
    }

    /**
     * Create an instance of {@link BCSSMESSAGE }
     * 
     */
    public BCSSMESSAGE createBCSSMESSAGE() {
        return new BCSSMESSAGE();
    }

    /**
     * Create an instance of {@link LCNOTIFP }
     * 
     */
    public LCNOTIFP createLCNOTIFP() {
        return new LCNOTIFP();
    }

    /**
     * Create an instance of {@link CSHPRIORITY }
     * 
     */
    public CSHPRIORITY createCSHPRIORITY() {
        return new CSHPRIORITY();
    }

    /**
     * Create an instance of {@link CANCELCONF }
     * 
     */
    public CANCELCONF createCANCELCONF() {
        return new CANCELCONF();
    }

    /**
     * Create an instance of {@link RESREQ }
     * 
     */
    public RESREQ createRESREQ() {
        return new RESREQ();
    }

    /**
     * Create an instance of {@link REPREQ }
     * 
     */
    public REPREQ createREPREQ() {
        return new REPREQ();
    }

    /**
     * Create an instance of {@link CRIT }
     * 
     */
    public CRIT createCRIT() {
        return new CRIT();
    }

    /**
     * Create an instance of {@link REP }
     * 
     */
    public REP createREP() {
        return new REP();
    }

    /**
     * Create an instance of {@link REPSEC }
     * 
     */
    public REPSEC createREPSEC() {
        return new REPSEC();
    }

    /**
     * Create an instance of {@link REPSECVAL }
     * 
     */
    public REPSECVAL createREPSECVAL() {
        return new REPSECVAL();
    }

    /**
     * Create an instance of {@link LCNOTIFS }
     * 
     */
    public LCNOTIFS createLCNOTIFS() {
        return new LCNOTIFS();
    }

    /**
     * Create an instance of {@link TSFEPRTY }
     * 
     */
    public TSFEPRTY createTSFEPRTY() {
        return new TSFEPRTY();
    }

    /**
     * Create an instance of {@link RTEP }
     * 
     */
    public RTEP createRTEP() {
        return new RTEP();
    }

    /**
     * Create an instance of {@link IM }
     * 
     */
    public IM createIM() {
        return new IM();
    }

    /**
     * Create an instance of {@link SNDR }
     * 
     */
    public SNDR createSNDR() {
        return new SNDR();
    }

    /**
     * Create an instance of {@link RCVR }
     * 
     */
    public RCVR createRCVR() {
        return new RCVR();
    }

    /**
     * Create an instance of {@link DEP }
     * 
     */
    public DEP createDEP() {
        return new DEP();
    }

    /**
     * Create an instance of {@link ENDORSEE }
     * 
     */
    public ENDORSEE createENDORSEE() {
        return new ENDORSEE();
    }

    /**
     * Create an instance of {@link AGREER }
     * 
     */
    public AGREER createAGREER() {
        return new AGREER();
    }

    /**
     * Create an instance of {@link FLOATINGRATEINFO }
     * 
     */
    public FLOATINGRATEINFO createFLOATINGRATEINFO() {
        return new FLOATINGRATEINFO();
    }

    /**
     * Create an instance of {@link CSHTRANSFER }
     * 
     */
    public CSHTRANSFER createCSHTRANSFER() {
        return new CSHTRANSFER();
    }

    /**
     * Create an instance of {@link CONSIGNTINST }
     * 
     */
    public CONSIGNTINST createCONSIGNTINST() {
        return new CONSIGNTINST();
    }

    /**
     * Create an instance of {@link CONSIGNTNOTE }
     * 
     */
    public CONSIGNTNOTE createCONSIGNTNOTE() {
        return new CONSIGNTNOTE();
    }

    /**
     * Create an instance of {@link PRESENTATIONNOTE }
     * 
     */
    public PRESENTATIONNOTE createPRESENTATIONNOTE() {
        return new PRESENTATIONNOTE();
    }

    /**
     * Create an instance of {@link RDMPNOTE }
     * 
     */
    public RDMPNOTE createRDMPNOTE() {
        return new RDMPNOTE();
    }

    /**
     * Create an instance of {@link REIINST }
     * 
     */
    public REIINST createREIINST() {
        return new REIINST();
    }

    /**
     * Create an instance of {@link REMINST }
     * 
     */
    public REMINST createREMINST() {
        return new REMINST();
    }

    /**
     * Create an instance of {@link NPRDMINST }
     * 
     */
    public NPRDMINST createNPRDMINST() {
        return new NPRDMINST();
    }

    /**
     * Create an instance of {@link NPWDINST }
     * 
     */
    public NPWDINST createNPWDINST() {
        return new NPWDINST();
    }

    /**
     * Create an instance of {@link INVACCTINFOINST }
     * 
     */
    public INVACCTINFOINST createINVACCTINFOINST() {
        return new INVACCTINFOINST();
    }

    /**
     * Create an instance of {@link MORTGAGERELEX }
     * 
     */
    public MORTGAGERELEX createMORTGAGERELEX() {
        return new MORTGAGERELEX();
    }

    /**
     * Create an instance of {@link MORTGAGESELREG }
     * 
     */
    public MORTGAGESELREG createMORTGAGESELREG() {
        return new MORTGAGESELREG();
    }

    /**
     * Create an instance of {@link OPENREPO }
     * 
     */
    public OPENREPO createOPENREPO() {
        return new OPENREPO();
    }

    /**
     * Create an instance of {@link PCH }
     * 
     */
    public PCH createPCH() {
        return new PCH();
    }

    /**
     * Create an instance of {@link CLOSEREPO }
     * 
     */
    public CLOSEREPO createCLOSEREPO() {
        return new CLOSEREPO();
    }

    /**
     * Create an instance of {@link BRKREPO }
     * 
     */
    public BRKREPO createBRKREPO() {
        return new BRKREPO();
    }

    /**
     * Create an instance of {@link BRKPRT }
     * 
     */
    public BRKPRT createBRKPRT() {
        return new BRKPRT();
    }

    /**
     * Create an instance of {@link REMPRT }
     * 
     */
    public REMPRT createREMPRT() {
        return new REMPRT();
    }

    /**
     * Create an instance of {@link SECSTLM }
     * 
     */
    public SECSTLM createSECSTLM() {
        return new SECSTLM();
    }

    /**
     * Create an instance of {@link OAT }
     * 
     */
    public OAT createOAT() {
        return new OAT();
    }

    /**
     * Create an instance of {@link SECBLK }
     * 
     */
    public SECBLK createSECBLK() {
        return new SECBLK();
    }

    /**
     * Create an instance of {@link LCNOTIFA }
     * 
     */
    public LCNOTIFA createLCNOTIFA() {
        return new LCNOTIFA();
    }

    /**
     * Create an instance of {@link LCNOTIFK }
     * 
     */
    public LCNOTIFK createLCNOTIFK() {
        return new LCNOTIFK();
    }

    /**
     * Create an instance of {@link CSHADVICE1 }
     * 
     */
    public CSHADVICE1 createCSHADVICE1() {
        return new CSHADVICE1();
    }

    /**
     * Create an instance of {@link SECLEG1 }
     * 
     */
    public SECLEG1 createSECLEG1() {
        return new SECLEG1();
    }

    /**
     * Create an instance of {@link SECGENLEG1 }
     * 
     */
    public SECGENLEG1 createSECGENLEG1() {
        return new SECGENLEG1();
    }

    /**
     * Create an instance of {@link FRSTLEG1 }
     * 
     */
    public FRSTLEG1 createFRSTLEG1() {
        return new FRSTLEG1();
    }

    /**
     * Create an instance of {@link REMAINPART }
     * 
     */
    public REMAINPART createREMAINPART() {
        return new REMAINPART();
    }

    /**
     * Create an instance of {@link FLTRANS }
     * 
     */
    public FLTRANS createFLTRANS() {
        return new FLTRANS();
    }

    /**
     * Create an instance of {@link STQUERY }
     * 
     */
    public STQUERY createSTQUERY() {
        return new STQUERY();
    }

    /**
     * Create an instance of {@link BASINFO }
     * 
     */
    public BASINFO createBASINFO() {
        return new BASINFO();
    }

    /**
     * Create an instance of {@link REGINFO }
     * 
     */
    public REGINFO createREGINFO() {
        return new REGINFO();
    }

    /**
     * Create an instance of {@link PAYINFO }
     * 
     */
    public PAYINFO createPAYINFO() {
        return new PAYINFO();
    }

    /**
     * Create an instance of {@link DVPUNDW }
     * 
     */
    public DVPUNDW createDVPUNDW() {
        return new DVPUNDW();
    }

    /**
     * Create an instance of {@link DVPCSHTRS }
     * 
     */
    public DVPCSHTRS createDVPCSHTRS() {
        return new DVPCSHTRS();
    }

    /**
     * Create an instance of {@link SECTRANS }
     * 
     */
    public SECTRANS createSECTRANS() {
        return new SECTRANS();
    }

    /**
     * Create an instance of {@link TRANSSTNOT }
     * 
     */
    public TRANSSTNOT createTRANSSTNOT() {
        return new TRANSSTNOT();
    }

    /**
     * Create an instance of {@link INHT }
     * 
     */
    public INHT createINHT() {
        return new INHT();
    }

    /**
     * Create an instance of {@link COURT }
     * 
     */
    public COURT createCOURT() {
        return new COURT();
    }

    /**
     * Create an instance of {@link PYMLIST }
     * 
     */
    public PYMLIST createPYMLIST() {
        return new PYMLIST();
    }

    /**
     * Create an instance of {@link PYMSN }
     * 
     */
    public PYMSN createPYMSN() {
        return new PYMSN();
    }

    /**
     * Create an instance of {@link PYMNOT }
     * 
     */
    public PYMNOT createPYMNOT() {
        return new PYMNOT();
    }

    /**
     * Create an instance of {@link RMEXCHANGE }
     * 
     */
    public RMEXCHANGE createRMEXCHANGE() {
        return new RMEXCHANGE();
    }

    /**
     * Create an instance of {@link RMRELEX }
     * 
     */
    public RMRELEX createRMRELEX() {
        return new RMRELEX();
    }

    /**
     * Create an instance of {@link RMREGEX }
     * 
     */
    public RMREGEX createRMREGEX() {
        return new RMREGEX();
    }

    /**
     * Create an instance of {@link ACCTMOV }
     * 
     */
    public ACCTMOV createACCTMOV() {
        return new ACCTMOV();
    }

    /**
     * Create an instance of {@link LCNOTIFRM }
     * 
     */
    public LCNOTIFRM createLCNOTIFRM() {
        return new LCNOTIFRM();
    }

    /**
     * Create an instance of {@link RINFO }
     * 
     */
    public RINFO createRINFO() {
        return new RINFO();
    }

    /**
     * Create an instance of {@link VMUN }
     * 
     */
    public VMUN createVMUN() {
        return new VMUN();
    }

    /**
     * Create an instance of {@link HLI }
     * 
     */
    public HLI createHLI() {
        return new HLI();
    }

    /**
     * Create an instance of {@link BROSTLM }
     * 
     */
    public BROSTLM createBROSTLM() {
        return new BROSTLM();
    }

    /**
     * Create an instance of {@link BROKERPRTY }
     * 
     */
    public BROKERPRTY createBROKERPRTY() {
        return new BROKERPRTY();
    }

    /**
     * Create an instance of {@link SELLPRTY }
     * 
     */
    public SELLPRTY createSELLPRTY() {
        return new SELLPRTY();
    }

    /**
     * Create an instance of {@link BUYPRTY }
     * 
     */
    public BUYPRTY createBUYPRTY() {
        return new BUYPRTY();
    }

    /**
     * Create an instance of {@link CONSREIINST }
     * 
     */
    public CONSREIINST createCONSREIINST() {
        return new CONSREIINST();
    }

    /**
     * Create an instance of {@link REISSUEINFO }
     * 
     */
    public REISSUEINFO createREISSUEINFO() {
        return new REISSUEINFO();
    }

    /**
     * Create an instance of {@link TXSCSHINFO }
     * 
     */
    public TXSCSHINFO createTXSCSHINFO() {
        return new TXSCSHINFO();
    }

    /**
     * Create an instance of {@link BILLFEES }
     * 
     */
    public BILLFEES createBILLFEES() {
        return new BILLFEES();
    }

    /**
     * Create an instance of {@link CONSREINOTE }
     * 
     */
    public CONSREINOTE createCONSREINOTE() {
        return new CONSREINOTE();
    }

    /**
     * Create an instance of {@link DEPFNB }
     * 
     */
    public DEPFNB createDEPFNB() {
        return new DEPFNB();
    }

    /**
     * Create an instance of {@link DEPFNBNOTE }
     * 
     */
    public DEPFNBNOTE createDEPFNBNOTE() {
        return new DEPFNBNOTE();
    }

    /**
     * Create an instance of {@link ISSUERATEINFOINST }
     * 
     */
    public ISSUERATEINFOINST createISSUERATEINFOINST() {
        return new ISSUERATEINFOINST();
    }

    /**
     * Create an instance of {@link DB }
     * 
     */
    public DB createDB() {
        return new DB();
    }

    /**
     * Create an instance of {@link CR }
     * 
     */
    public CR createCR() {
        return new CR();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STLM_DT")
    public JAXBElement<String> createSTLMDT(String value) {
        return new JAXBElement<String>(_STLMDT_QNAME, String.class, null, value);
    }

}
