//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.def;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}REP_SEC" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="REP_NM" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="REP_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PRTY_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SNDR_REF" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PAGE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TTL_PAGE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STLM_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "repsec"
})
@XmlRootElement(name = "REP")
public class REP {

    @XmlElement(name = "REP_SEC")
    protected List<REPSEC> repsec;
    @XmlAttribute(name = "REP_NM")
    @XmlSchemaType(name = "anySimpleType")
    protected String repnm;
    @XmlAttribute(name = "REP_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String repid;
    @XmlAttribute(name = "PRTY_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String prtyid;
    @XmlAttribute(name = "SNDR_REF", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String sndrref;
    @XmlAttribute(name = "PAGE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String page;
    @XmlAttribute(name = "TTL_PAGE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ttlpage;
    @XmlAttribute(name = "STLM_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String stlmdt;

    /**
     * Gets the value of the repsec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repsec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREPSEC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link REPSEC }
     * 
     * 
     */
    public List<REPSEC> getREPSEC() {
        if (repsec == null) {
            repsec = new ArrayList<REPSEC>();
        }
        return this.repsec;
    }

    /**
     * Gets the value of the repnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPNM() {
        return repnm;
    }

    /**
     * Sets the value of the repnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPNM(String value) {
        this.repnm = value;
    }

    /**
     * Gets the value of the repid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPID() {
        return repid;
    }

    /**
     * Sets the value of the repid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPID(String value) {
        this.repid = value;
    }

    /**
     * Gets the value of the prtyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRTYID() {
        return prtyid;
    }

    /**
     * Sets the value of the prtyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRTYID(String value) {
        this.prtyid = value;
    }

    /**
     * Gets the value of the sndrref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSNDRREF() {
        return sndrref;
    }

    /**
     * Sets the value of the sndrref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSNDRREF(String value) {
        this.sndrref = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAGE() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAGE(String value) {
        this.page = value;
    }

    /**
     * Gets the value of the ttlpage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTTLPAGE() {
        return ttlpage;
    }

    /**
     * Sets the value of the ttlpage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTTLPAGE(String value) {
        this.ttlpage = value;
    }

    /**
     * Gets the value of the stlmdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTLMDT() {
        return stlmdt;
    }

    /**
     * Sets the value of the stlmdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTLMDT(String value) {
        this.stlmdt = value;
    }

}
