//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="TAX_AMT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDMP_TAX_AMT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CLSD_TAX_AMT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FUT_TAX_AMT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "TAX_IMP")
public class TAXIMP {

    @XmlAttribute(name = "TAX_AMT")
    @XmlSchemaType(name = "anySimpleType")
    protected String taxamt;
    @XmlAttribute(name = "RDMP_TAX_AMT")
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmptaxamt;
    @XmlAttribute(name = "CLSD_TAX_AMT")
    @XmlSchemaType(name = "anySimpleType")
    protected String clsdtaxamt;
    @XmlAttribute(name = "FUT_TAX_AMT")
    @XmlSchemaType(name = "anySimpleType")
    protected String futtaxamt;

    /**
     * Gets the value of the taxamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXAMT() {
        return taxamt;
    }

    /**
     * Sets the value of the taxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXAMT(String value) {
        this.taxamt = value;
    }

    /**
     * Gets the value of the rdmptaxamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMPTAXAMT() {
        return rdmptaxamt;
    }

    /**
     * Sets the value of the rdmptaxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMPTAXAMT(String value) {
        this.rdmptaxamt = value;
    }

    /**
     * Gets the value of the clsdtaxamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLSDTAXAMT() {
        return clsdtaxamt;
    }

    /**
     * Sets the value of the clsdtaxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLSDTAXAMT(String value) {
        this.clsdtaxamt = value;
    }

    /**
     * Gets the value of the futtaxamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFUTTAXAMT() {
        return futtaxamt;
    }

    /**
     * Sets the value of the futtaxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFUTTAXAMT(String value) {
        this.futtaxamt = value;
    }

}
