//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DNM_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDMP_SEC_AMT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TAX_AMT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "UNDERWRITINGPART")
public class UNDERWRITINGPART {

    @XmlAttribute(name = "DNM_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String dnmid;
    @XmlAttribute(name = "RDMP_SEC_AMT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmpsecamt;
    @XmlAttribute(name = "TAX_AMT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String taxamt;

    /**
     * Gets the value of the dnmid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDNMID() {
        return dnmid;
    }

    /**
     * Sets the value of the dnmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDNMID(String value) {
        this.dnmid = value;
    }

    /**
     * Gets the value of the rdmpsecamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMPSECAMT() {
        return rdmpsecamt;
    }

    /**
     * Sets the value of the rdmpsecamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMPSECAMT(String value) {
        this.rdmpsecamt = value;
    }

    /**
     * Gets the value of the taxamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXAMT() {
        return taxamt;
    }

    /**
     * Sets the value of the taxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXAMT(String value) {
        this.taxamt = value;
    }

}
