//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.metrics.bean.BDLeg;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="PRICE" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="IDAYS" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ACC_INT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ACC_INT_TAX" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "BD_LEG")
public class BDLEG {

    @XmlAttribute(name = "PRICE")
    @XmlSchemaType(name = "anySimpleType")
    protected String price;
    @XmlAttribute(name = "IDAYS")
    @XmlSchemaType(name = "anySimpleType")
    protected String idays;
    @XmlAttribute(name = "ACC_INT")
    @XmlSchemaType(name = "anySimpleType")
    protected String accint;
    @XmlAttribute(name = "ACC_INT_TAX")
    @XmlSchemaType(name = "anySimpleType")
    protected String accinttax;
    
    public BDLEG(BDLeg instance) {
    	this( instance.getPrice(), instance.getIdays(), instance.getAccint(), instance.getAccinttax() );
    }
    
    public BDLEG(String price, String idays, String accint, String accinttax) {
		super();
		this.price = price;
		this.idays = idays;
		this.accint = accint;
		this.accinttax = accinttax;
	}

	/**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRICE() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRICE(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the idays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDAYS() {
        return idays;
    }

    /**
     * Sets the value of the idays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDAYS(String value) {
        this.idays = value;
    }

    /**
     * Gets the value of the accint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCINT() {
        return accint;
    }

    /**
     * Sets the value of the accint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCINT(String value) {
        this.accint = value;
    }

    /**
     * Gets the value of the accinttax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCINTTAX() {
        return accinttax;
    }

    /**
     * Sets the value of the accinttax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCINTTAX(String value) {
        this.accinttax = value;
    }

}
