//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DENOMINATION" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="REF_TYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="REF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ORIG_INST_REF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PRTY_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CPRTY_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="THRD_PRTY_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDMP_VAL" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "denomination"
})
@XmlRootElement(name = "CANCEL_CONF")
public class CANCELCONF {

    @XmlElement(name = "DENOMINATION")
    protected List<DENOMINATION> denomination;
    @XmlAttribute(name = "REF_TYPE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String reftype;
    @XmlAttribute(name = "REF")
    @XmlSchemaType(name = "anySimpleType")
    protected String ref;
    @XmlAttribute(name = "ORIG_INST_REF")
    @XmlSchemaType(name = "anySimpleType")
    protected String originstref;
    @XmlAttribute(name = "PRTY_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String prtyid;
    @XmlAttribute(name = "CPRTY_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String cprtyid;
    @XmlAttribute(name = "THRD_PRTY_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String thrdprtyid;
    @XmlAttribute(name = "RDMP_VAL")
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmpval;

    public CANCELCONF() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
     * Gets the value of the denomination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the denomination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDENOMINATION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DENOMINATION }
     * 
     * 
     */
    public List<DENOMINATION> getDENOMINATION() {
        if (denomination == null) {
            denomination = new ArrayList<DENOMINATION>();
        }
        return this.denomination;
    }

    /**
     * Gets the value of the reftype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFTYPE() {
        return reftype;
    }

    /**
     * Sets the value of the reftype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFTYPE(String value) {
        this.reftype = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREF() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREF(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the originstref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORIGINSTREF() {
        return originstref;
    }

    /**
     * Sets the value of the originstref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORIGINSTREF(String value) {
        this.originstref = value;
    }

    /**
     * Gets the value of the prtyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRTYID() {
        return prtyid;
    }

    /**
     * Sets the value of the prtyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRTYID(String value) {
        this.prtyid = value;
    }

    /**
     * Gets the value of the cprtyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPRTYID() {
        return cprtyid;
    }

    /**
     * Sets the value of the cprtyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPRTYID(String value) {
        this.cprtyid = value;
    }

    /**
     * Gets the value of the thrdprtyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTHRDPRTYID() {
        return thrdprtyid;
    }

    /**
     * Sets the value of the thrdprtyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTHRDPRTYID(String value) {
        this.thrdprtyid = value;
    }

    /**
     * Gets the value of the rdmpval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMPVAL() {
        return rdmpval;
    }

    /**
     * Sets the value of the rdmpval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMPVAL(String value) {
        this.rdmpval = value;
    }

}
