//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CSH_CCY">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="TWD"/>
 *             &lt;enumeration value="USD"/>
 *             &lt;enumeration value="AUD"/>
 *             &lt;enumeration value="EUR"/>
 *             &lt;enumeration value="JPY"/>
 *             &lt;enumeration value="CNY"/>
 *             &lt;enumeration value="ZAR"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CSH_AMT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="AFT_TAX_AMT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="REMIT_FEE" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "CSH_LEG")
public class CSHLEG {

    @XmlAttribute(name = "CSH_CCY")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cshccy;
    @XmlAttribute(name = "CSH_AMT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String cshamt;
    @XmlAttribute(name = "AFT_TAX_AMT")
    @XmlSchemaType(name = "anySimpleType")
    protected String afttaxamt;
    @XmlAttribute(name = "REMIT_FEE")
    @XmlSchemaType(name = "anySimpleType")
    protected String remitfee;

    /**
     * Gets the value of the cshccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSHCCY() {
        return cshccy;
    }

    /**
     * Sets the value of the cshccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSHCCY(String value) {
        this.cshccy = value;
    }

    /**
     * Gets the value of the cshamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSHAMT() {
        return cshamt;
    }

    /**
     * Sets the value of the cshamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSHAMT(String value) {
        this.cshamt = value;
    }

    /**
     * Gets the value of the afttaxamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAFTTAXAMT() {
        return afttaxamt;
    }

    /**
     * Sets the value of the afttaxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAFTTAXAMT(String value) {
        this.afttaxamt = value;
    }

    /**
     * Gets the value of the remitfee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREMITFEE() {
        return remitfee;
    }

    /**
     * Sets the value of the remitfee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREMITFEE(String value) {
        this.remitfee = value;
    }

}
