//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}CPRTY"/>
 *         &lt;element ref="{}DENOMINATION"/>
 *         &lt;element ref="{}CSH_LEG"/>
 *         &lt;element ref="{}RECEIVER_BANK"/>
 *         &lt;element ref="{}FLOATING_RATE_INFO"/>
 *       &lt;/choice>
 *       &lt;attribute name="NCD_NO" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ISS_RT_TYPE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ISIN" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CSH_SYS" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="TWD"/>
 *             &lt;enumeration value="USD"/>
 *             &lt;enumeration value="AUD"/>
 *             &lt;enumeration value="EUR"/>
 *             &lt;enumeration value="JPY"/>
 *             &lt;enumeration value="CNY"/>
 *             &lt;enumeration value="ZAR"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ISS_TYPE" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="5"/>
 *             &lt;enumeration value="6"/>
 *             &lt;enumeration value="7"/>
 *             &lt;enumeration value="8"/>
 *             &lt;enumeration value="9"/>
 *             &lt;enumeration value="10"/>
 *             &lt;enumeration value="11"/>
 *             &lt;enumeration value="12"/>
 *             &lt;enumeration value="13"/>
 *             &lt;enumeration value="14"/>
 *             &lt;enumeration value="15"/>
 *             &lt;enumeration value="31"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ISSR_NM" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ISSR_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PRTY_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FVAL" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ISS_DAYS" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ISS_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="MAT_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TH_MAT_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DEP_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ISS_RT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDMP_AMT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="INT_IND" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ISSR_BUS_CODE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ISSR_GRP_ID" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="BRNCH_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="COUNTRY_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DEPR_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NCD_PAY_BANK" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PSDB_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="AMT_TYPE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="REG_IND">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Y"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cprtyOrDENOMINATIONOrCSHLEG"
})
@XmlRootElement(name = "DEP_FNB")
public class DEPFNB {

    public DEPFNB() {
		super();
		// TODO Auto-generated constructor stub
	}

	@XmlElements({
        @XmlElement(name = "CPRTY", type = CPRTY.class),
        @XmlElement(name = "DENOMINATION", type = DENOMINATION.class),
        @XmlElement(name = "CSH_LEG", type = CSHLEG.class),
        @XmlElement(name = "RECEIVER_BANK", type = RECEIVERBANK.class),
        @XmlElement(name = "FLOATING_RATE_INFO", type = FLOATINGRATEINFO.class)
    })
    protected List<Object> cprtyOrDENOMINATIONOrCSHLEG;
    @XmlAttribute(name = "NCD_NO")
    @XmlSchemaType(name = "anySimpleType")
    protected String ncdno;
    @XmlAttribute(name = "ISS_RT_TYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String issrttype;
    @XmlAttribute(name = "ISIN", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String isin;
    @XmlAttribute(name = "CSH_SYS", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cshsys;
    @XmlAttribute(name = "ISS_TYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isstype;
    @XmlAttribute(name = "ISSR_NM", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String issrnm;
    @XmlAttribute(name = "ISSR_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String issrid;
    @XmlAttribute(name = "PRTY_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String prtyid;
    @XmlAttribute(name = "FVAL", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fval;
    @XmlAttribute(name = "ISS_DAYS", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String issdays;
    @XmlAttribute(name = "ISS_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String issdt;
    @XmlAttribute(name = "MAT_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String matdt;
    @XmlAttribute(name = "TH_MAT_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String thmatdt;
    @XmlAttribute(name = "DEP_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String depdt;
    @XmlAttribute(name = "ISS_RT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String issrt;
    @XmlAttribute(name = "RDMP_AMT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmpamt;
    @XmlAttribute(name = "INT_IND", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String intind;
    @XmlAttribute(name = "ISSR_BUS_CODE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String issrbuscode;
    @XmlAttribute(name = "ISSR_GRP_ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String issrgrpid;
    @XmlAttribute(name = "BRNCH_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String brnchid;
    @XmlAttribute(name = "COUNTRY_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String countryid;
    @XmlAttribute(name = "DEPR_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String deprid;
    @XmlAttribute(name = "NCD_PAY_BANK")
    @XmlSchemaType(name = "anySimpleType")
    protected String ncdpaybank;
    @XmlAttribute(name = "PSDB_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String psdbid;
    @XmlAttribute(name = "AMT_TYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String amttype;
    @XmlAttribute(name = "REG_IND")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String regind;

    /**
     * Gets the value of the cprtyOrDENOMINATIONOrCSHLEG property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cprtyOrDENOMINATIONOrCSHLEG property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCPRTYOrDENOMINATIONOrCSHLEG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CPRTY }
     * {@link DENOMINATION }
     * {@link CSHLEG }
     * {@link RECEIVERBANK }
     * {@link FLOATINGRATEINFO }
     * 
     * 
     */
    public List<Object> getCPRTYOrDENOMINATIONOrCSHLEG() {
        if (cprtyOrDENOMINATIONOrCSHLEG == null) {
            cprtyOrDENOMINATIONOrCSHLEG = new ArrayList<Object>();
        }
        return this.cprtyOrDENOMINATIONOrCSHLEG;
    }

    /**
     * Gets the value of the ncdno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCDNO() {
        return ncdno;
    }

    /**
     * Sets the value of the ncdno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCDNO(String value) {
        this.ncdno = value;
    }

    /**
     * Gets the value of the issrttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSRTTYPE() {
        return issrttype;
    }

    /**
     * Sets the value of the issrttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSRTTYPE(String value) {
        this.issrttype = value;
    }

    /**
     * Gets the value of the isin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISIN() {
        return isin;
    }

    /**
     * Sets the value of the isin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISIN(String value) {
        this.isin = value;
    }

    /**
     * Gets the value of the cshsys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSHSYS() {
        return cshsys;
    }

    /**
     * Sets the value of the cshsys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSHSYS(String value) {
        this.cshsys = value;
    }

    /**
     * Gets the value of the isstype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSTYPE() {
        return isstype;
    }

    /**
     * Sets the value of the isstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSTYPE(String value) {
        this.isstype = value;
    }

    /**
     * Gets the value of the issrnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSRNM() {
        return issrnm;
    }

    /**
     * Sets the value of the issrnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSRNM(String value) {
        this.issrnm = value;
    }

    /**
     * Gets the value of the issrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSRID() {
        return issrid;
    }

    /**
     * Sets the value of the issrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSRID(String value) {
        this.issrid = value;
    }

    /**
     * Gets the value of the prtyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRTYID() {
        return prtyid;
    }

    /**
     * Sets the value of the prtyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRTYID(String value) {
        this.prtyid = value;
    }

    /**
     * Gets the value of the fval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFVAL() {
        return fval;
    }

    /**
     * Sets the value of the fval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFVAL(String value) {
        this.fval = value;
    }

    /**
     * Gets the value of the issdays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSDAYS() {
        return issdays;
    }

    /**
     * Sets the value of the issdays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSDAYS(String value) {
        this.issdays = value;
    }

    /**
     * Gets the value of the issdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSDT() {
        return issdt;
    }

    /**
     * Sets the value of the issdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSDT(String value) {
        this.issdt = value;
    }

    /**
     * Gets the value of the matdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATDT() {
        return matdt;
    }

    /**
     * Sets the value of the matdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATDT(String value) {
        this.matdt = value;
    }

    /**
     * Gets the value of the thmatdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTHMATDT() {
        return thmatdt;
    }

    /**
     * Sets the value of the thmatdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTHMATDT(String value) {
        this.thmatdt = value;
    }

    /**
     * Gets the value of the depdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEPDT() {
        return depdt;
    }

    /**
     * Sets the value of the depdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEPDT(String value) {
        this.depdt = value;
    }

    /**
     * Gets the value of the issrt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSRT() {
        return issrt;
    }

    /**
     * Sets the value of the issrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSRT(String value) {
        this.issrt = value;
    }

    /**
     * Gets the value of the rdmpamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMPAMT() {
        return rdmpamt;
    }

    /**
     * Sets the value of the rdmpamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMPAMT(String value) {
        this.rdmpamt = value;
    }

    /**
     * Gets the value of the intind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTIND() {
        return intind;
    }

    /**
     * Sets the value of the intind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTIND(String value) {
        this.intind = value;
    }

    /**
     * Gets the value of the issrbuscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSRBUSCODE() {
        return issrbuscode;
    }

    /**
     * Sets the value of the issrbuscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSRBUSCODE(String value) {
        this.issrbuscode = value;
    }

    /**
     * Gets the value of the issrgrpid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSRGRPID() {
        return issrgrpid;
    }

    /**
     * Sets the value of the issrgrpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSRGRPID(String value) {
        this.issrgrpid = value;
    }

    /**
     * Gets the value of the brnchid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBRNCHID() {
        return brnchid;
    }

    /**
     * Sets the value of the brnchid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBRNCHID(String value) {
        this.brnchid = value;
    }

    /**
     * Gets the value of the countryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTRYID() {
        return countryid;
    }

    /**
     * Sets the value of the countryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTRYID(String value) {
        this.countryid = value;
    }

    /**
     * Gets the value of the deprid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEPRID() {
        return deprid;
    }

    /**
     * Sets the value of the deprid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEPRID(String value) {
        this.deprid = value;
    }

    /**
     * Gets the value of the ncdpaybank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCDPAYBANK() {
        return ncdpaybank;
    }

    /**
     * Sets the value of the ncdpaybank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCDPAYBANK(String value) {
        this.ncdpaybank = value;
    }

    /**
     * Gets the value of the psdbid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPSDBID() {
        return psdbid;
    }

    /**
     * Sets the value of the psdbid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPSDBID(String value) {
        this.psdbid = value;
    }

    /**
     * Gets the value of the amttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMTTYPE() {
        return amttype;
    }

    /**
     * Sets the value of the amttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMTTYPE(String value) {
        this.amttype = value;
    }

    /**
     * Gets the value of the regind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREGIND() {
        return regind;
    }

    /**
     * Sets the value of the regind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREGIND(String value) {
        this.regind = value;
    }

}
