//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}CSH_LEG"/>
 *         &lt;element ref="{}TAX_IMP"/>
 *         &lt;element ref="{}REMAIN_PART"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cshlegOrTAXIMPOrREMAINPART"
})
@XmlRootElement(name = "FRST_LEG1")
public class FRSTLEG1 {

    public FRSTLEG1() {
		super();
		// TODO Auto-generated constructor stub
	}

	@XmlElements({
        @XmlElement(name = "CSH_LEG", type = CSHLEG.class),
        @XmlElement(name = "TAX_IMP", type = TAXIMP.class),
        @XmlElement(name = "REMAIN_PART", type = REMAINPART.class)
    })
    protected List<Object> cshlegOrTAXIMPOrREMAINPART;

    /**
     * Gets the value of the cshlegOrTAXIMPOrREMAINPART property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cshlegOrTAXIMPOrREMAINPART property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCSHLEGOrTAXIMPOrREMAINPART().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CSHLEG }
     * {@link TAXIMP }
     * {@link REMAINPART }
     * 
     * 
     */
    public List<Object> getCSHLEGOrTAXIMPOrREMAINPART() {
        if (cshlegOrTAXIMPOrREMAINPART == null) {
            cshlegOrTAXIMPOrREMAINPART = new ArrayList<Object>();
        }
        return this.cshlegOrTAXIMPOrREMAINPART;
    }

}
