//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}PRTY"/>
 *         &lt;element ref="{}CPRTY"/>
 *         &lt;element ref="{}SEC_LEG"/>
 *       &lt;/choice>
 *       &lt;attribute name="REF_TYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="REF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CREF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="REPO_CNTR_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RM_CNTR_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NEW_REPO_CNTR_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NEW_RM_CNTR_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FT_REF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CSH_AMT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="XTR_INT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ST" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ST_RSN" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SCND_CNTR_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="THRD_CNTR_ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SNDR_REF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SCND_SNDR_REF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NARR" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prtyOrCPRTYOrSECLEG"
})
@XmlRootElement(name = "LC_NOTIFRM")
public class LCNOTIFRM {

    public LCNOTIFRM() {
		super();
		// TODO Auto-generated constructor stub
	}

	@XmlElements({
        @XmlElement(name = "PRTY", type = PRTY.class),
        @XmlElement(name = "CPRTY", type = CPRTY.class),
        @XmlElement(name = "SEC_LEG", type = SECLEG.class)
    })
    protected List<Object> prtyOrCPRTYOrSECLEG;
    @XmlAttribute(name = "REF_TYPE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String reftype;
    @XmlAttribute(name = "REF")
    @XmlSchemaType(name = "anySimpleType")
    protected String ref;
    @XmlAttribute(name = "CREF")
    @XmlSchemaType(name = "anySimpleType")
    protected String cref;
    @XmlAttribute(name = "REPO_CNTR_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String repocntrid;
    @XmlAttribute(name = "RM_CNTR_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String rmcntrid;
    @XmlAttribute(name = "NEW_REPO_CNTR_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String newrepocntrid;
    @XmlAttribute(name = "NEW_RM_CNTR_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String newrmcntrid;
    @XmlAttribute(name = "FT_REF")
    @XmlSchemaType(name = "anySimpleType")
    protected String ftref;
    @XmlAttribute(name = "CSH_AMT")
    @XmlSchemaType(name = "anySimpleType")
    protected String cshamt;
    @XmlAttribute(name = "XTR_INT")
    @XmlSchemaType(name = "anySimpleType")
    protected String xtrint;
    @XmlAttribute(name = "ST", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String st;
    @XmlAttribute(name = "ST_RSN")
    @XmlSchemaType(name = "anySimpleType")
    protected String strsn;
    @XmlAttribute(name = "SCND_CNTR_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String scndcntrid;
    @XmlAttribute(name = "THRD_CNTR_ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String thrdcntrid;
    @XmlAttribute(name = "SNDR_REF")
    @XmlSchemaType(name = "anySimpleType")
    protected String sndrref;
    @XmlAttribute(name = "SCND_SNDR_REF")
    @XmlSchemaType(name = "anySimpleType")
    protected String scndsndrref;
    @XmlAttribute(name = "NARR")
    @XmlSchemaType(name = "anySimpleType")
    protected String narr;

    /**
     * Gets the value of the prtyOrCPRTYOrSECLEG property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prtyOrCPRTYOrSECLEG property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPRTYOrCPRTYOrSECLEG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PRTY }
     * {@link CPRTY }
     * {@link SECLEG }
     * 
     * 
     */
    public List<Object> getPRTYOrCPRTYOrSECLEG() {
        if (prtyOrCPRTYOrSECLEG == null) {
            prtyOrCPRTYOrSECLEG = new ArrayList<Object>();
        }
        return this.prtyOrCPRTYOrSECLEG;
    }

    /**
     * Gets the value of the reftype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFTYPE() {
        return reftype;
    }

    /**
     * Sets the value of the reftype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFTYPE(String value) {
        this.reftype = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREF() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREF(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the cref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREF() {
        return cref;
    }

    /**
     * Sets the value of the cref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREF(String value) {
        this.cref = value;
    }

    /**
     * Gets the value of the repocntrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPOCNTRID() {
        return repocntrid;
    }

    /**
     * Sets the value of the repocntrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPOCNTRID(String value) {
        this.repocntrid = value;
    }

    /**
     * Gets the value of the rmcntrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRMCNTRID() {
        return rmcntrid;
    }

    /**
     * Sets the value of the rmcntrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRMCNTRID(String value) {
        this.rmcntrid = value;
    }

    /**
     * Gets the value of the newrepocntrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNEWREPOCNTRID() {
        return newrepocntrid;
    }

    /**
     * Sets the value of the newrepocntrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNEWREPOCNTRID(String value) {
        this.newrepocntrid = value;
    }

    /**
     * Gets the value of the newrmcntrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNEWRMCNTRID() {
        return newrmcntrid;
    }

    /**
     * Sets the value of the newrmcntrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNEWRMCNTRID(String value) {
        this.newrmcntrid = value;
    }

    /**
     * Gets the value of the ftref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTREF() {
        return ftref;
    }

    /**
     * Sets the value of the ftref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTREF(String value) {
        this.ftref = value;
    }

    /**
     * Gets the value of the cshamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSHAMT() {
        return cshamt;
    }

    /**
     * Sets the value of the cshamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSHAMT(String value) {
        this.cshamt = value;
    }

    /**
     * Gets the value of the xtrint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXTRINT() {
        return xtrint;
    }

    /**
     * Sets the value of the xtrint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXTRINT(String value) {
        this.xtrint = value;
    }

    /**
     * Gets the value of the st property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getST() {
        return st;
    }

    /**
     * Sets the value of the st property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setST(String value) {
        this.st = value;
    }

    /**
     * Gets the value of the strsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRSN() {
        return strsn;
    }

    /**
     * Sets the value of the strsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRSN(String value) {
        this.strsn = value;
    }

    /**
     * Gets the value of the scndcntrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCNDCNTRID() {
        return scndcntrid;
    }

    /**
     * Sets the value of the scndcntrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCNDCNTRID(String value) {
        this.scndcntrid = value;
    }

    /**
     * Gets the value of the thrdcntrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTHRDCNTRID() {
        return thrdcntrid;
    }

    /**
     * Sets the value of the thrdcntrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTHRDCNTRID(String value) {
        this.thrdcntrid = value;
    }

    /**
     * Gets the value of the sndrref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSNDRREF() {
        return sndrref;
    }

    /**
     * Sets the value of the sndrref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSNDRREF(String value) {
        this.sndrref = value;
    }

    /**
     * Gets the value of the scndsndrref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCNDSNDRREF() {
        return scndsndrref;
    }

    /**
     * Sets the value of the scndsndrref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCNDSNDRREF(String value) {
        this.scndsndrref = value;
    }

    /**
     * Gets the value of the narr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNARR() {
        return narr;
    }

    /**
     * Sets the value of the narr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNARR(String value) {
        this.narr = value;
    }

}
