//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SEC_LEG" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="PRTY_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HOLDER_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ACCT_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="MAT_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FVAL" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TAX_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "secleg"
})
@XmlRootElement(name = "NPWD_INST")
public class NPWDINST {

    public NPWDINST() {
		super();
		// TODO Auto-generated constructor stub
	}

	@XmlElement(name = "SEC_LEG")
    protected List<SECLEG> secleg;
    @XmlAttribute(name = "PRTY_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String prtyid;
    @XmlAttribute(name = "HOLDER_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String holderid;
    @XmlAttribute(name = "ACCT_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String acctid;
    @XmlAttribute(name = "MAT_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String matdt;
    @XmlAttribute(name = "FVAL", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fval;
    @XmlAttribute(name = "TAX_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String taxdt;

    /**
     * Gets the value of the secleg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secleg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSECLEG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SECLEG }
     * 
     * 
     */
    public List<SECLEG> getSECLEG() {
        if (secleg == null) {
            secleg = new ArrayList<SECLEG>();
        }
        return this.secleg;
    }

    /**
     * Gets the value of the prtyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRTYID() {
        return prtyid;
    }

    /**
     * Sets the value of the prtyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRTYID(String value) {
        this.prtyid = value;
    }

    /**
     * Gets the value of the holderid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOLDERID() {
        return holderid;
    }

    /**
     * Sets the value of the holderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOLDERID(String value) {
        this.holderid = value;
    }

    /**
     * Gets the value of the acctid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCTID() {
        return acctid;
    }

    /**
     * Sets the value of the acctid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCTID(String value) {
        this.acctid = value;
    }

    /**
     * Gets the value of the matdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATDT() {
        return matdt;
    }

    /**
     * Sets the value of the matdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATDT(String value) {
        this.matdt = value;
    }

    /**
     * Gets the value of the fval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFVAL() {
        return fval;
    }

    /**
     * Sets the value of the fval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFVAL(String value) {
        this.fval = value;
    }

    /**
     * Gets the value of the taxdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXDT() {
        return taxdt;
    }

    /**
     * Sets the value of the taxdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXDT(String value) {
        this.taxdt = value;
    }

}
