//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="REF" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ISIN" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PSDB_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ISS_TYPE" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="5"/>
 *             &lt;enumeration value="6"/>
 *             &lt;enumeration value="7"/>
 *             &lt;enumeration value="8"/>
 *             &lt;enumeration value="9"/>
 *             &lt;enumeration value="10"/>
 *             &lt;enumeration value="11"/>
 *             &lt;enumeration value="12"/>
 *             &lt;enumeration value="13"/>
 *             &lt;enumeration value="14"/>
 *             &lt;enumeration value="15"/>
 *             &lt;enumeration value="31"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="FVAL" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TTL_RDMP_VAL" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDMP_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TAX_AMT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TTL_TAX_IMP" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CSH_SYS">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="TWD"/>
 *             &lt;enumeration value="USD"/>
 *             &lt;enumeration value="AUD"/>
 *             &lt;enumeration value="EUR"/>
 *             &lt;enumeration value="JPY"/>
 *             &lt;enumeration value="CNY"/>
 *             &lt;enumeration value="ZAR"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="FISC_AMT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="INTB_CODE" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "RDMP_NOTE")
public class RDMPNOTE {

    @XmlAttribute(name = "REF", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ref;
    @XmlAttribute(name = "ISIN", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String isin;
    @XmlAttribute(name = "PSDB_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String psdbid;
    @XmlAttribute(name = "ISS_TYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isstype;
    @XmlAttribute(name = "FVAL", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fval;
    @XmlAttribute(name = "TTL_RDMP_VAL", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ttlrdmpval;
    @XmlAttribute(name = "RDMP_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmpdt;
    @XmlAttribute(name = "TAX_AMT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String taxamt;
    @XmlAttribute(name = "TTL_TAX_IMP", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ttltaximp;
    @XmlAttribute(name = "CSH_SYS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cshsys;
    @XmlAttribute(name = "FISC_AMT")
    @XmlSchemaType(name = "anySimpleType")
    protected String fiscamt;
    @XmlAttribute(name = "INTB_CODE")
    @XmlSchemaType(name = "anySimpleType")
    protected String intbcode;

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREF() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREF(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the isin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISIN() {
        return isin;
    }

    /**
     * Sets the value of the isin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISIN(String value) {
        this.isin = value;
    }

    /**
     * Gets the value of the psdbid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPSDBID() {
        return psdbid;
    }

    /**
     * Sets the value of the psdbid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPSDBID(String value) {
        this.psdbid = value;
    }

    /**
     * Gets the value of the isstype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSTYPE() {
        return isstype;
    }

    /**
     * Sets the value of the isstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSTYPE(String value) {
        this.isstype = value;
    }

    /**
     * Gets the value of the fval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFVAL() {
        return fval;
    }

    /**
     * Sets the value of the fval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFVAL(String value) {
        this.fval = value;
    }

    /**
     * Gets the value of the ttlrdmpval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTTLRDMPVAL() {
        return ttlrdmpval;
    }

    /**
     * Sets the value of the ttlrdmpval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTTLRDMPVAL(String value) {
        this.ttlrdmpval = value;
    }

    /**
     * Gets the value of the rdmpdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMPDT() {
        return rdmpdt;
    }

    /**
     * Sets the value of the rdmpdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMPDT(String value) {
        this.rdmpdt = value;
    }

    /**
     * Gets the value of the taxamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXAMT() {
        return taxamt;
    }

    /**
     * Sets the value of the taxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXAMT(String value) {
        this.taxamt = value;
    }

    /**
     * Gets the value of the ttltaximp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTTLTAXIMP() {
        return ttltaximp;
    }

    /**
     * Sets the value of the ttltaximp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTTLTAXIMP(String value) {
        this.ttltaximp = value;
    }

    /**
     * Gets the value of the cshsys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSHSYS() {
        return cshsys;
    }

    /**
     * Sets the value of the cshsys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSHSYS(String value) {
        this.cshsys = value;
    }

    /**
     * Gets the value of the fiscamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFISCAMT() {
        return fiscamt;
    }

    /**
     * Sets the value of the fiscamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFISCAMT(String value) {
        this.fiscamt = value;
    }

    /**
     * Gets the value of the intbcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTBCODE() {
        return intbcode;
    }

    /**
     * Sets the value of the intbcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTBCODE(String value) {
        this.intbcode = value;
    }

}
