//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="UN_CAP_AMT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="UN_INT_AMT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Deprecated
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "REMAIN_PART")
public class REMAINPART {

    public REMAINPART() {
		super();
		// TODO Auto-generated constructor stub
	}

	@XmlAttribute(name = "UN_CAP_AMT")
    @XmlSchemaType(name = "anySimpleType")
    protected String uncapamt;
    @XmlAttribute(name = "UN_INT_AMT")
    @XmlSchemaType(name = "anySimpleType")
    protected String unintamt;

    /**
     * Gets the value of the uncapamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNCAPAMT() {
        return uncapamt;
    }

    /**
     * Sets the value of the uncapamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNCAPAMT(String value) {
        this.uncapamt = value;
    }

    /**
     * Gets the value of the unintamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNINTAMT() {
        return unintamt;
    }

    /**
     * Sets the value of the unintamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNINTAMT(String value) {
        this.unintamt = value;
    }

}
