//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CPRTY_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="REF" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="REF_TYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RMT_RSN" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BANK_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ISIN" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TDCC_ACCT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PSTB_PRTY_NM" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDMER_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDMER_ACCT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CH_ACCT_NM" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="EN_ACCT_NM" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STLM_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDM_DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CSH_CCY">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="TWD"/>
 *             &lt;enumeration value="USD"/>
 *             &lt;enumeration value="AUD"/>
 *             &lt;enumeration value="EUR"/>
 *             &lt;enumeration value="JPY"/>
 *             &lt;enumeration value="CNY"/>
 *             &lt;enumeration value="ZAR"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CAP_AMT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BAL_AMT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="INT_AMT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TRANS_FEE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PB_ST" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ORG_SNDR_REF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BAL_TYPE" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "R_INFO")
public class RINFO {

    @XmlAttribute(name = "CPRTY_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String cprtyid;
    @XmlAttribute(name = "REF", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ref;
    @XmlAttribute(name = "REF_TYPE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String reftype;
    @XmlAttribute(name = "RMT_RSN")
    @XmlSchemaType(name = "anySimpleType")
    protected String rmtrsn;
    @XmlAttribute(name = "BANK_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bankid;
    @XmlAttribute(name = "ISIN", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String isin;
    @XmlAttribute(name = "TDCC_ACCT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tdccacct;
    @XmlAttribute(name = "PSTB_PRTY_NM")
    @XmlSchemaType(name = "anySimpleType")
    protected String pstbprtynm;
    @XmlAttribute(name = "RDMER_ID", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmerid;
    @XmlAttribute(name = "RDMER_ACCT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmeracct;
    @XmlAttribute(name = "CH_ACCT_NM")
    @XmlSchemaType(name = "anySimpleType")
    protected String chacctnm;
    @XmlAttribute(name = "EN_ACCT_NM", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String enacctnm;
    @XmlAttribute(name = "STLM_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String stlmdt;
    @XmlAttribute(name = "RDM_DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmdt;
    @XmlAttribute(name = "CSH_CCY")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cshccy;
    @XmlAttribute(name = "CAP_AMT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String capamt;
    @XmlAttribute(name = "BAL_AMT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String balamt;
    @XmlAttribute(name = "INT_AMT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String intamt;
    @XmlAttribute(name = "TRANS_FEE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String transfee;
    @XmlAttribute(name = "PB_ST", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String pbst;
    @XmlAttribute(name = "ORG_SNDR_REF")
    @XmlSchemaType(name = "anySimpleType")
    protected String orgsndrref;
    @XmlAttribute(name = "BAL_TYPE")
    @XmlSchemaType(name = "anySimpleType")
    protected String baltype;

    /**
     * Gets the value of the cprtyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPRTYID() {
        return cprtyid;
    }

    /**
     * Sets the value of the cprtyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPRTYID(String value) {
        this.cprtyid = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREF() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREF(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the reftype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFTYPE() {
        return reftype;
    }

    /**
     * Sets the value of the reftype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFTYPE(String value) {
        this.reftype = value;
    }

    /**
     * Gets the value of the rmtrsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRMTRSN() {
        return rmtrsn;
    }

    /**
     * Sets the value of the rmtrsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRMTRSN(String value) {
        this.rmtrsn = value;
    }

    /**
     * Gets the value of the bankid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBANKID() {
        return bankid;
    }

    /**
     * Sets the value of the bankid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBANKID(String value) {
        this.bankid = value;
    }

    /**
     * Gets the value of the isin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISIN() {
        return isin;
    }

    /**
     * Sets the value of the isin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISIN(String value) {
        this.isin = value;
    }

    /**
     * Gets the value of the tdccacct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDCCACCT() {
        return tdccacct;
    }

    /**
     * Sets the value of the tdccacct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDCCACCT(String value) {
        this.tdccacct = value;
    }

    /**
     * Gets the value of the pstbprtynm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPSTBPRTYNM() {
        return pstbprtynm;
    }

    /**
     * Sets the value of the pstbprtynm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPSTBPRTYNM(String value) {
        this.pstbprtynm = value;
    }

    /**
     * Gets the value of the rdmerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMERID() {
        return rdmerid;
    }

    /**
     * Sets the value of the rdmerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMERID(String value) {
        this.rdmerid = value;
    }

    /**
     * Gets the value of the rdmeracct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMERACCT() {
        return rdmeracct;
    }

    /**
     * Sets the value of the rdmeracct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMERACCT(String value) {
        this.rdmeracct = value;
    }

    /**
     * Gets the value of the chacctnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHACCTNM() {
        return chacctnm;
    }

    /**
     * Sets the value of the chacctnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHACCTNM(String value) {
        this.chacctnm = value;
    }

    /**
     * Gets the value of the enacctnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENACCTNM() {
        return enacctnm;
    }

    /**
     * Sets the value of the enacctnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENACCTNM(String value) {
        this.enacctnm = value;
    }

    /**
     * Gets the value of the stlmdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTLMDT() {
        return stlmdt;
    }

    /**
     * Sets the value of the stlmdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTLMDT(String value) {
        this.stlmdt = value;
    }

    /**
     * Gets the value of the rdmdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMDT() {
        return rdmdt;
    }

    /**
     * Sets the value of the rdmdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMDT(String value) {
        this.rdmdt = value;
    }

    /**
     * Gets the value of the cshccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSHCCY() {
        return cshccy;
    }

    /**
     * Sets the value of the cshccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSHCCY(String value) {
        this.cshccy = value;
    }

    /**
     * Gets the value of the capamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAPAMT() {
        return capamt;
    }

    /**
     * Sets the value of the capamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAPAMT(String value) {
        this.capamt = value;
    }

    /**
     * Gets the value of the balamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBALAMT() {
        return balamt;
    }

    /**
     * Sets the value of the balamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBALAMT(String value) {
        this.balamt = value;
    }

    /**
     * Gets the value of the intamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTAMT() {
        return intamt;
    }

    /**
     * Sets the value of the intamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTAMT(String value) {
        this.intamt = value;
    }

    /**
     * Gets the value of the transfee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSFEE() {
        return transfee;
    }

    /**
     * Sets the value of the transfee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSFEE(String value) {
        this.transfee = value;
    }

    /**
     * Gets the value of the pbst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPBST() {
        return pbst;
    }

    /**
     * Sets the value of the pbst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPBST(String value) {
        this.pbst = value;
    }

    /**
     * Gets the value of the orgsndrref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGSNDRREF() {
        return orgsndrref;
    }

    /**
     * Sets the value of the orgsndrref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGSNDRREF(String value) {
        this.orgsndrref = value;
    }

    /**
     * Gets the value of the baltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBALTYPE() {
        return baltype;
    }

    /**
     * Sets the value of the baltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBALTYPE(String value) {
        this.baltype = value;
    }

}
