//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="REF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ORG_SNDR_REF" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ORG_REF_TYPE" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ORG_REF_NO" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ST_QUERY")
public class STQUERY {

    public STQUERY() {
		super();
		// TODO Auto-generated constructor stub
	}

	@XmlAttribute(name = "REF")
    @XmlSchemaType(name = "anySimpleType")
    protected String ref;
    @XmlAttribute(name = "ORG_SNDR_REF")
    @XmlSchemaType(name = "anySimpleType")
    protected String orgsndrref;
    @XmlAttribute(name = "ORG_REF_TYPE")
    @XmlSchemaType(name = "anySimpleType")
    protected String orgreftype;
    @XmlAttribute(name = "ORG_REF_NO")
    @XmlSchemaType(name = "anySimpleType")
    protected String orgrefno;

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREF() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREF(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the orgsndrref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGSNDRREF() {
        return orgsndrref;
    }

    /**
     * Sets the value of the orgsndrref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGSNDRREF(String value) {
        this.orgsndrref = value;
    }

    /**
     * Gets the value of the orgreftype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGREFTYPE() {
        return orgreftype;
    }

    /**
     * Sets the value of the orgreftype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGREFTYPE(String value) {
        this.orgreftype = value;
    }

    /**
     * Gets the value of the orgrefno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGREFNO() {
        return orgrefno;
    }

    /**
     * Sets the value of the orgrefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGREFNO(String value) {
        this.orgrefno = value;
    }

}
