//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.03 at 08:32:50 AM CST 
//


package com.metrics.xml.message.tdcc.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CSH_SYS">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="TWD"/>
 *             &lt;enumeration value="USD"/>
 *             &lt;enumeration value="AUD"/>
 *             &lt;enumeration value="EUR"/>
 *             &lt;enumeration value="JPY"/>
 *             &lt;enumeration value="CNY"/>
 *             &lt;enumeration value="ZAR"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="REI_AFT_TAX_AMT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="REI_TTL_CSH_AMT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDMP_TTL_FACE_VAL" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDMP_FACE_VAL" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RDMP_TAX_AMT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "TXS_CSH_INFO")
public class TXSCSHINFO {

    @XmlAttribute(name = "CSH_SYS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cshsys;
    @XmlAttribute(name = "REI_AFT_TAX_AMT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String reiafttaxamt;
    @XmlAttribute(name = "REI_TTL_CSH_AMT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String reittlcshamt;
    @XmlAttribute(name = "RDMP_TTL_FACE_VAL")
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmpttlfaceval;
    @XmlAttribute(name = "RDMP_FACE_VAL")
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmpfaceval;
    @XmlAttribute(name = "RDMP_TAX_AMT")
    @XmlSchemaType(name = "anySimpleType")
    protected String rdmptaxamt;

    /**
     * Gets the value of the cshsys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSHSYS() {
        return cshsys;
    }

    /**
     * Sets the value of the cshsys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSHSYS(String value) {
        this.cshsys = value;
    }

    /**
     * Gets the value of the reiafttaxamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREIAFTTAXAMT() {
        return reiafttaxamt;
    }

    /**
     * Sets the value of the reiafttaxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREIAFTTAXAMT(String value) {
        this.reiafttaxamt = value;
    }

    /**
     * Gets the value of the reittlcshamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREITTLCSHAMT() {
        return reittlcshamt;
    }

    /**
     * Sets the value of the reittlcshamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREITTLCSHAMT(String value) {
        this.reittlcshamt = value;
    }

    /**
     * Gets the value of the rdmpttlfaceval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMPTTLFACEVAL() {
        return rdmpttlfaceval;
    }

    /**
     * Sets the value of the rdmpttlfaceval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMPTTLFACEVAL(String value) {
        this.rdmpttlfaceval = value;
    }

    /**
     * Gets the value of the rdmpfaceval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMPFACEVAL() {
        return rdmpfaceval;
    }

    /**
     * Sets the value of the rdmpfaceval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMPFACEVAL(String value) {
        this.rdmpfaceval = value;
    }

    /**
     * Gets the value of the rdmptaxamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDMPTAXAMT() {
        return rdmptaxamt;
    }

    /**
     * Sets the value of the rdmptaxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDMPTAXAMT(String value) {
        this.rdmptaxamt = value;
    }

}
